### ISSUE TITLE
Mejorar listados de miembros y de todo lo demas

### ISSUE THREAD

**Issue by alagos** [cltorresfe/members#57]

**Comment by cltorresfe** [comment]
- [x] Mejorar Listado de Miembros
- [x] Mejorar Listado de Iglesias
- [x] Mejorar Listado de Ministerios
- [x] Mejorar Listado de Cargos

**Comment by cltorresfe** [comment]
Listo para que lo revises @alagos  PR #90
